presizely_api:
    resource: "@PresizelyAPIBundle/Resources/config/routing.yml"
    prefix:   /api

presizely_user:
    resource: "@PresizelyUserBundle/Resources/config/routing.yml"
    prefix:   /

presizely_products:
    resource: "@PresizelyProductsBundle/Resources/config/routing.yml"
    prefix:   /products

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register-bis

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/login.xml"
    prefix: /login

_console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    prefix: /_console
